node {
 try {
 
 emailext body: 'Assignment Case Study 3', subject: 'Pipeline Job is in progress', to: 'brad4287@gmail.com'
 
 stage('Git CheckOut') {
    git branch: 'main', url: 'https://github.com/brad4287/CaseStudy3.git'
 }
 
 def project_path="Jenkins/petclinic-code"
 
 dir(project_path) {
 
 stage('Maven Clean') {
    sh 'mvn clean'
 }
 
  stage('Maven Compile') {
    sh 'mvn compile'
 }
 
 stage('Maven Testing') {
    sh 'mvn test'
 }
 
 stage('Maven Package') {
    sh 'mvn package'
 }
 
 stage('Archive Artifacts') {
    archive 'target/*.war'
 }

 stage('Archive into Artifactory') {
rtUpload (
    serverId: '1',
    spec: '''{
          "files": [
            {
              "pattern": "**/*.war",
			  "target": "generic-snapshot/"
              
            }
         ]
    }''',
 

    buildName: 'petclinic',
    buildNumber: '7'
)
rtPublishBuildInfo (
    serverId: '1',

     buildName: 'petclinic',
    buildNumber: '7'
)
}

 stage('SonarQube Code Analysis')
    {
        withSonarQubeEnv('SonarQube') {
                sh 'mvn clean package sonar:sonar'
        }
    }


 stage('Getting Ready For Ansible') {
    sh 'cp -rf target/*.war ../../Ansible/Tomcat/files/'
    sh "echo '<h1> Task Build ID: ${env.BUILD_DISPLAY_NAME}</h1>' > ../../Ansible/Tomcat/files/jenkins.html"
 }
  
 }

 def project_ansible="Ansible/Tomcat/"
 dir(project_ansible){
  
 stage('Ansible Deployment') {
    sh 'ansible-playbook webserver.yaml'
 }
 }
 
 } catch (err) {
     emailext body: "<b>Devops Assignment</b><br>\n <br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL build: ${env.BUILD_URL} <br> ${err}", cc: '', charset: 'UTF-8', from: 'jenkins@mindtree.com', mimeType: 'text/html', replyTo: '', subject: "Pipeline ERROR CI: Project name -> ${env.JOB_NAME}", to: "pal.rashmi@gmail.com"
}
}

